# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: deploy-and-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.22.0
      - run: | 
          make dist
          cd web
          yarn install
          yarn build
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build
          FOLDER: web/build 


