name: web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.22.0
      - run: | 
          make dist
          cd web
          yarn install
          yarn build
      - uses: EndBug/add-and-commit@v9
        with:
          add: ./web/build --force
          new_branch: build


