name: web

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: 0.22.0
      - run: | 
          make dist
          cd web
          yarn install
          yarn build
      - uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: build # The branch the action should deploy to.
          FOLDER: web/build # The folder the action should deploy.


