FROM node:latest

# set working directory
WORKDIR /app

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/node_modules/.bin:$PATH

COPY . . 
# RUN yarn install
RUN yarn global add serve
# RUN yarn build
# add app
EXPOSE 3000
# EXPOSE 3000/udp
# start app
CMD ["serve", "-s", "build"]
